set_ifndef(RISCVWIN_TOOLCHAIN_PATH "$ENV{RISCVWIN_TOOLCHAIN_PATH}")
set(       RISCVWIN_TOOLCHAIN_PATH ${RISCVWIN_TOOLCHAIN_PATH} CACHE PATH "riscwin install directory")
assert(    RISCVWIN_TOOLCHAIN_PATH "RISCVWIN_TOOLCHAIN_PATH is not set")

if(NOT EXISTS ${RISCVWIN_TOOLCHAIN_PATH})
  message(FATAL_ERROR "Nothing found at RISCVWIN_TOOLCHAIN_PATH: '${RISCVWIN_TOOLCHAIN_PATH}'")
endif()

set(TOOLCHAIN_HOME ${RISCVWIN_TOOLCHAIN_PATH})

set(COMPILER gcc)

set(CROSS_COMPILE_TARGET riscv-none-embed)
set(SYSROOT_TARGET       riscv-none-embed)

set(CROSS_COMPILE ${TOOLCHAIN_HOME}/bin/${CROSS_COMPILE_TARGET}-)
set(SYSROOT_DIR   ${TOOLCHAIN_HOME}/${SYSROOT_TARGET})
set(TOOLCHAIN_HAS_NEWLIB ON CACHE BOOL "True if toolchain supports newlib")
